# 浏览器标签页中的标题分隔符
title_separator: " | "

# 浏览器标签页小图标
favicon: "https://dev.oneall.eu.org/favicon.webp"

sidebar_extra_html: |- # 侧边栏额外html
    <a href="/rss2.xml">RSS</a><br>
    <a href="/sitemap.xml">Sitemap</a><br>
    <a href="mailto:dev@oneall.eu.org">Email</a><br>

excerpt_length: 150 # 简介文章最大字数

# CORS跨域代理, 留空则禁用友链RSS获取, 请求URL将会拼接到此代理地址之后
# 默认地址可能会失效, 详见 https://dev.oneall.eu.org/archives/52
cors_proxy: "https://vercel.oneall.eu.org/api/vap?"

# 随机站点介绍, 每行一个
random_intro:
    - 路漫漫其修远兮，吾将上下而求索
    - 天将降大任于是人也，必先苦其心志，劳其筋骨，饿其体肤，空乏其身，行拂乱其所为
    - 惜秦皇汉武，略输文采；唐宗宋祖，稍逊风骚。俱往矣，数风流人物，还看今朝。

# 链接页面, 格式如下:
# - {
#   avatar: "图标地址",
#   title: "名称",
#   url: "链接地址",
#   description: "描述",
#   rss: "RSS地址(可选)"
# }
links:
    - {
          avatar: "https://dev.oneall.eu.org/favicon.webp",
          title: "r1a dev",
          url: "https://dev.oneall.eu.org",
          description: "r1a的开发记录/博客",
          rss: "https://dev.oneall.eu.org/feed",
      }
    - {
          avatar: "https://blog.522.plus/wp-content/uploads/2024/05/chungbin_avatar.jpg",
          title: "522小椿的小站",
          url: "https://blog.522.plus",
          description: "一个爱好二次元的个人博客小站",
          rss: "https://blog.522.plus/?feed=rss2",
      }
    - {
          avatar: "https://filecdn.runoneall.nyc.mn/BlogResource/favicon.webp",
          title: "Runoneall's Blog",
          url: "https://runoneall.github.io",
          description: "一介互联网闲散之人",
          rss: "https://runoneall.github.io/atom.xml",
      }
    - {
          avatar: "https://img.yyyyt.top/avatar/avatar",
          title: "Yyyyt的文档站",
          url: "https://docs.yyyyt.top",
          description: "World is Bad or Worse",
          rss: "https://docs.yyyyt.top/rss.xml",
      }
    - {
          avatar: "https://1ctrl-cv.github.io/img/avatar.png",
          title: "B84F2246",
          url: "https://1ctrl-cv.github.io",
          description: "TECH OTAKUS SAVE THEWORLD!",
          rss: "https://1ctrl-cv.github.io/atom.xml",
      }
    - {
          avatar: "https://creeper005bili.github.io/img/avatar.png",
          title: "Creeper005の小站",
          url: "https://creeper005bili.github.io",
          description: "Creeper005の坐牢日常",
      }
    - {
          avatar: "https://s.rmimg.com/2025-03-22/1742638401-544915-c2x7ns29av.png",
          title: "Qrasa的小站",
          url: "https://blog.qrasa.cn",
          description: "记录一些活着的日常",
          rss: "https://blog.qrasa.cn/feed",
      }
    - {
          avatar: "https://blog.toserk.top/logo.webp",
          title: "Toserk博客",
          url: "https://blog.toserk.top",
          description: "Toserk的个人博客",
      }
    - {
          avatar: "https://www.maodream.com/favicon.ico",
          title: "MaoDream",
          url: "https://www.maodream.com",
          description: "MaoDream的个人博客",
          rss: "https://www.maodream.com/feed",
      }
    - {
          avatar: "https://static.mcio.dev/mrxiaom.top/images/avatar-new.jpg",
          title: "人间工作P",
          url: "https://producer.mrxiaom.top",
          description: "我每天都好困…",
      }
    - {
          avatar: "https://www.leorain.cn/images/logo.png",
          title: "leorain",
          url: "https://www.leorain.cn",
          description: "一个对技术和生活充满热爱的文艺型技术青年",
      }
    - {
          avatar: "https://mcarc.spectrollay.com/minecraft_repository_test/images/logo/Starmoon_logo.png",
          title: "星月Minecraft版本库",
          url: "https://spectrollay.github.io/minecraft_repository",
          description: "一个开放共享的全版本Minecraft下载站",
      }
    - {
          avatar: "https://www.puddingkc.com/api/v2/objects/avatar/2cfgqfbuk0clj9t0md.webp",
          title: "PuddingKC's Blog",
          url: "https://www.puddingkc.com",
          description: "愿你所热爱的依旧不减当年。",
          rss: "https://www.puddingkc.com/feed",
      }
    - {
          avatar: "https://blog.yeqing.net/upload/ea055268c8792945de3b9c8d00e1cd08.jpeg",
          title: "夜轻Blog",
          url: "https://blog.yeqing.net",
          description: "一个人",
          rss: "https://blog.yeqing.net/rss.xml",
      }

extra_css: "" # 额外CSS

extra_js: |- # 额外javascript (footer)
    console.log(String.raw`
                ___              __
          _____<  /____ _   ____/ /___  _   __
         / ___// // __ `+ "`" + String.raw`/  / __  // _ \| | / /
        / /   / // /_/ /  / /_/ //  __/| |/ /
       /_/   /_/ \__,_/   \__,_/ \___/ |___/

    LET THE UNFAIRNESS OF THE WORLD BOW BEFORE ME
    `)

extra_html: "" # 额外html (body末尾)
