name: Build And Deploy to Public Branch

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@main
              with:
                  fetch-depth: 0

            - name: Set up Node.js LTS
              uses: actions/setup-node@main
              with:
                  node-version: latest

            - name: Install dependencies and generate
              run: |
                  npm install
                  npm run clean
                  npm run build

            - name: Sync to theme branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.REPO_TOKEN }}
                  publish_dir: ./themes/hexo-theme-old-fashion
                  destination_dir: ./
                  publish_branch: theme
                  keep_files: false


            - name: Deploy to public branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.REPO_TOKEN }}
                  publish_dir: ./public
                  destination_dir: ./
                  publish_branch: public
                  keep_files: false
