name: Build And Deploy to Public Branch

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@main
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Set up Node.js LTS
              uses: actions/setup-node@main
              with:
                  node-version: latest

            - name: Install Hexo CLI
              run: npm install hexo

            - name: Install dependencies and generate
              run: |
                  npm install
                  npx hexo clean
                  npx hexo generate

            - name: Deploy to public branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.REPO_TOKEN }}
                  publish_dir: ./public
                  destination_dir: ./
                  publish_branch: public
                  keep_files: false
